version: '3'

services:
  nginx:
    build:
      context: ./nginx
    volumes:
      - images_volume:/home/app/web/images
      - data_volume:/home/app/web/data
    ports:
      - '80:80'
    depends_on:
      - web
  web:
    build: .
    command: pipenv run python api.py
    volumes:
      - images_volume:/home/app/web/images
    expose:
      - 8000

volumes:
  images_volume:
  data_volume:
